// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OficinaDigital.Infrastructure.Persistencia;

#nullable disable

namespace OficinaDigital.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(OficinaDbContext))]
    [Migration("20260831055122_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OficinaDigital.Domain.Atendimento.OrdemDeServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AbertaEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescricaoDoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MotivoCancelamento")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Numero"), 1000L);

                    b.Property<string>("ObservacaoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("OrcamentoAprovado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OrcamentoVigenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_OrdensDeServico_Numero");

                    b.HasIndex("Status");

                    b.HasIndex("VeiculoId");

                    b.ToTable("OrdensDeServico", "atendimento");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Cadastro.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", "cadastro");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Cadastro.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Veiculos", "cadastro");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Catalogo.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sku");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Pecas_Sku");

                    b.ToTable("Pecas", "catalogo");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Catalogo.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TempoPadraoExecucao")
                        .HasColumnType("int")
                        .HasColumnName("TempoPadraoMinutos");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Servicos_Nome");

                    b.ToTable("Servicos", "catalogo");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Estoque.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Unidade")
                        .HasColumnType("int");

                    b.Property<decimal>("_estoqueMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("EstoqueMinimo");

                    b.Property<decimal>("_reservado")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Reservado");

                    b.Property<decimal>("_saldo")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Saldo");

                    b.HasKey("Id");

                    b.HasIndex("PecaId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItensDeEstoque_PecaId");

                    b.ToTable("ItensDeEstoque", "estoque");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenhaSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.ToTable("Usuarios", "identidade");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Orcamentos.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrdemDeServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("VersaoVigente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdemDeServicoId");

                    b.ToTable("Orcamentos", "orcamento");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Atendimento.OrdemDeServico", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Atendimento.ItemDePeca", "ItensDePeca", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AguardandoAprovacaoDoCliente")
                                .HasColumnType("bit");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)");

                            b1.Property<Guid>("OrdemDeServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Origem")
                                .HasColumnType("int");

                            b1.Property<Guid>("PecaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("PrecoCongelado")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoCongelado");

                            b1.Property<decimal>("Quantidade")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("RegistradoEm")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrdemDeServicoId");

                            b1.HasIndex("PecaId");

                            b1.ToTable("ItensDePecaDaOs", "atendimento");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDeServicoId");
                        });

                    b.OwnsMany("OficinaDigital.Domain.Atendimento.ItemDeServico", "ItensDeServico", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AguardandoAprovacaoDoCliente")
                                .HasColumnType("bit");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("OrdemDeServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Origem")
                                .HasColumnType("int");

                            b1.Property<decimal>("PrecoCongelado")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoCongelado");

                            b1.Property<DateTime>("RegistradoEm")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TempoPadraoMinutos")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("OrdemDeServicoId");

                            b1.HasIndex("ServicoId");

                            b1.ToTable("ItensDeServicoDaOs", "atendimento");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDeServicoId");
                        });

                    b.OwnsOne("OficinaDigital.Domain.Atendimento.ValueObjects.JanelaDeExecucao", "Execucao", b1 =>
                        {
                            b1.Property<Guid>("OrdemDeServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("Fim")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExecucaoFim");

                            b1.Property<DateTime?>("Inicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExecucaoInicio");

                            b1.Property<DateTime?>("SuspensaEm")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExecucaoSuspensaEm");

                            b1.Property<long>("TempoAguardandoAprovacao")
                                .HasColumnType("bigint")
                                .HasColumnName("TempoAguardandoAprovacaoTicks");

                            b1.HasKey("OrdemDeServicoId");

                            b1.ToTable("OrdensDeServico", "atendimento");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDeServicoId");
                        });

                    b.Navigation("Execucao")
                        .IsRequired();

                    b.Navigation("ItensDePeca");

                    b.Navigation("ItensDeServico");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Cadastro.Cliente", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Cadastro.ValueObjects.Contato", "Contatos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Canal")
                                .HasColumnType("int");

                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("ClienteId");

                            b1.ToTable("ClienteContatos", "cadastro");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("OficinaDigital.Domain.Cadastro.ValueObjects.CpfCnpj", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("Documento");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("TipoPessoa");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Numero")
                                .IsUnique()
                                .HasDatabaseName("IX_Clientes_Documento");

                            b1.ToTable("Clientes", "cadastro");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("OficinaDigital.Domain.Cadastro.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("NumeroEndereco");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Uf");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes", "cadastro");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Contatos");

                    b.Navigation("Documento")
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Cadastro.Veiculo", b =>
                {
                    b.OwnsOne("OficinaDigital.Domain.Cadastro.ValueObjects.Placa", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Padrao")
                                .HasColumnType("int")
                                .HasColumnName("PadraoPlaca");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("Placa");

                            b1.HasKey("VeiculoId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("IX_Veiculos_Placa");

                            b1.ToTable("Veiculos", "cadastro");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.Navigation("Placa")
                        .IsRequired();
                });

            modelBuilder.Entity("OficinaDigital.Domain.Catalogo.Peca", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Common.PrecoVigente", "Precos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("PecaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.Property<DateOnly>("VigenteDe")
                                .HasColumnType("date")
                                .HasColumnName("VigenteDe");

                            b1.HasKey("Id");

                            b1.HasIndex("PecaId");

                            b1.ToTable("PecaPrecos", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("PecaId");
                        });

                    b.Navigation("Precos");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Catalogo.Servico", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Common.PrecoVigente", "Precos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.Property<DateOnly>("VigenteDe")
                                .HasColumnType("date")
                                .HasColumnName("VigenteDe");

                            b1.HasKey("Id");

                            b1.HasIndex("ServicoId");

                            b1.ToTable("ServicoPrecos", "catalogo");

                            b1.WithOwner()
                                .HasForeignKey("ServicoId");
                        });

                    b.Navigation("Precos");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Estoque.ItemEstoque", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Estoque.MovimentoEstoque", "Movimentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Motivo")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<Guid?>("OrdemDeServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantidade")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("RegistradoEm")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("SaldoResultante")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemEstoqueId");

                            b1.ToTable("MovimentosDeEstoque", "estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsMany("OficinaDigital.Domain.Estoque.ReservaEstoque", "Reservas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("OrdemDeServicoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantidade")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("ReservadaEm")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemEstoqueId");

                            b1.HasIndex("OrdemDeServicoId")
                                .HasDatabaseName("IX_ReservasDeEstoque_OsId");

                            b1.ToTable("ReservasDeEstoque", "estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.Navigation("Movimentos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("OficinaDigital.Domain.Orcamentos.Orcamento", b =>
                {
                    b.OwnsMany("OficinaDigital.Domain.Orcamentos.VersaoOrcamento", "Versoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("EnviadoEm")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("GeradoEm")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.Property<Guid>("OrcamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Total")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Total");

                            b1.HasKey("Id");

                            b1.HasIndex("OrcamentoId");

                            b1.ToTable("VersoesDeOrcamento", "orcamento");

                            b1.WithOwner()
                                .HasForeignKey("OrcamentoId");

                            b1.OwnsMany("OficinaDigital.Domain.Orcamentos.ItemOrcado", "Itens", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Descricao")
                                        .IsRequired()
                                        .HasMaxLength(240)
                                        .HasColumnType("nvarchar(240)");

                                    b2.Property<decimal>("PrecoUnitario")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PrecoUnitario");

                                    b2.Property<decimal>("Quantidade")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)");

                                    b2.Property<Guid>("ReferenciaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Tipo")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("VersaoOrcamentoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VersaoOrcamentoId");

                                    b2.ToTable("ItensDeOrcamento", "orcamento");

                                    b2.WithOwner()
                                        .HasForeignKey("VersaoOrcamentoId");
                                });

                            b1.OwnsOne("OficinaDigital.Domain.Orcamentos.ValueObjects.RespostaCliente", "Resposta", b2 =>
                                {
                                    b2.Property<Guid>("VersaoOrcamentoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Decisao")
                                        .HasColumnType("int")
                                        .HasColumnName("Decisao");

                                    b2.Property<DateTime>("RespondidoEm")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("RespondidoEm");

                                    b2.HasKey("VersaoOrcamentoId");

                                    b2.ToTable("VersoesDeOrcamento", "orcamento");

                                    b2.WithOwner()
                                        .HasForeignKey("VersaoOrcamentoId");
                                });

                            b1.Navigation("Itens");

                            b1.Navigation("Resposta");
                        });

                    b.Navigation("Versoes");
                });
#pragma warning restore 612, 618
        }
    }
}
